# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_HelperFunctions.initialization.ipynb (unless otherwise specified).

__all__ = ['resolution_default', 'train_lr', 'list_all_imported_modules']

# Cell

### import libraries
from fastai import *
from fastai.vision import *
from operator import *
from types import SimpleNamespace
import re

## remotved from fastai v2
# from fastai.utils.mem import *
# from fastai.callbacks import *
# from fastai.callbacks.hooks import *

# Cell

import nibabel as nib
from nibabel import *
from imageio import *
import scipy as sp
import matplotlib.pyplot as plt

# Cell

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="torch.nn.functional")
warnings.filterwarnings("ignore", category=UserWarning, module="torch.nn.Modules")
warnings.filterwarnings("ignore", category=UserWarning, module="torchvision.models")

# Cell
resolution_default = (350,1024,350) # for IMG
train_lr = 1e-4

# Cell
def list_all_imported_modules():
    '''
    check current imported modules
    Ref: https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html#case-4-importing-from-parent-directory
    '''
    import pkgutil
    search_path = None # set to None to see all modules importable from sys.path
    all_modules = [x[1] for x in pkgutil.iter_modules(path=search_path)]
    print(all_modules)
    return all_modules
